"""Validate and serialize resolved desktop operations."""

from .keymap import (
    BUTTON_NUMBERS,
    KEY_ALIASES,
    KEY_NAMES,
    KEYSYMS,
    POINTER_BUTTONS,
    PRESSABLE_KEYS,
    KeymapError,
    guest_button,
    guest_key,
    key_chord,
    key_press,
)
from .protocol import (
    ACTION_CONTRACT,
    ACTION_SCHEMA_VERSION,
    ALL_POINTER_BUTTON_MASK,
    BUTTON_MASKS,
    ExecutionError,
    ExecutionReceipt,
    HeldStateError,
    InputAudit,
    build_action_request,
    expected_atomic_input_state,
    lower_guest_operations,
    pointer_mask_for_buttons,
)

__all__ = [
    "ACTION_CONTRACT",
    "ACTION_SCHEMA_VERSION",
    "ALL_POINTER_BUTTON_MASK",
    "BUTTON_MASKS",
    "BUTTON_NUMBERS",
    "KEY_ALIASES",
    "KEY_NAMES",
    "KEYSYMS",
    "POINTER_BUTTONS",
    "PRESSABLE_KEYS",
    "ExecutionError",
    "ExecutionReceipt",
    "HeldStateError",
    "InputAudit",
    "KeymapError",
    "build_action_request",
    "expected_atomic_input_state",
    "guest_button",
    "guest_key",
    "key_chord",
    "key_press",
    "lower_guest_operations",
    "pointer_mask_for_buttons",
]
